on: [push, pull_request]

jobs:
  missing:
    name: List missing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./test/test.sh --missing
      - run: ./test/test.sh --coverage >> $GITHUB_ENV
      - uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_COVERAGE_SECRET }}
          gistID: 73fb3c58350c58b623f221fc237def62
          filename: tcr_coverage.json
          label: coverage
          message: ${{ env.COVERED }}/${{ env.TOTAL }}
          namedLogo: GitHub
          valColorRange: ${{ env.TOTAL }}
          minColorRange: ${{ env.REQUIRED }}
          maxColorRange: ${{ env.TOTAL }}
