on:
  workflow_dispatch:

jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    name: Test all (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: ./test/test.sh
