on: [push, pull_request]
jobs:
  code:
    strategy:
      matrix:
        tests: [datastructures, geometry, graph, math, other, string, template, --missing]
        os: [ubuntu-latest, ubuntu-22.04]
    name: Test  ${{ matrix.tests }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: ./test/test.sh ${{ matrix.tests }}

  pdf:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    name: Test pdf (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install latexmk texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-lang-german texlive-fonts-extra
      - run: make
