on:
  push:
    paths:
      - 'content/**'
      - 'Makefile'
  pull_request:
    paths:
      - 'content/**'
      - 'Makefile'
  workflow_dispatch:

jobs:
  pdf_22-04:
    name: Test pdf (ubuntu-22.04)
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install latexmk texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-lang-german texlive-fonts-extra
      - run: make

  pdf_latest:
    name: Test pdf (ubuntu-latest)
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install latexmk texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-lang-german texlive-fonts-extra
      - run: make
      - uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_COVERAGE_SECRET }}
          gist_id: 73fb3c58350c58b623f221fc237def62
          file_path: tcr.pdf
          file_type: binary
